<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

namespace Memphisphp\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Messages</code>
 */
class Messages extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pb.Msg msg = 1;</code>
     */
    private $msg;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Memphisphp\Pb\Msg[]|\Google\Protobuf\Internal\RepeatedField $msg
     * }
     */
    public function __construct($data = NULL) {
        \Memphisphp\Metadata\Msg::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Msg msg = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Msg msg = 1;</code>
     * @param \Memphisphp\Pb\Msg[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMsg($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Memphisphp\Pb\Msg::class);
        $this->msg = $arr;

        return $this;
    }

}

