<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto

namespace Memphisphp\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.MessagesRet</code>
 */
class MessagesRet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 messages = 1;</code>
     */
    protected $messages = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $messages
     * }
     */
    public function __construct($data = NULL) {
        \Memphisphp\Metadata\Station::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 messages = 1;</code>
     * @return int
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Generated from protobuf field <code>int32 messages = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMessages($var)
    {
        GPBUtil::checkInt32($var);
        $this->messages = $var;

        return $this;
    }

}

