<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto

namespace Memphisphp\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.RetentionOpt</code>
 */
class RetentionOpt extends \Google\Protobuf\Internal\Message
{
    protected $retentions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Memphisphp\Pb\MaxMessageAgeSecondsRet $mmasret
     *     @type \Memphisphp\Pb\MessagesRet $msgret
     *     @type \Memphisphp\Pb\BytesRet $bret
     *     @type \Memphisphp\Pb\AckBasedRet $abret
     * }
     */
    public function __construct($data = NULL) {
        \Memphisphp\Metadata\Station::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.MaxMessageAgeSecondsRet mmasret = 1;</code>
     * @return \Memphisphp\Pb\MaxMessageAgeSecondsRet|null
     */
    public function getMmasret()
    {
        return $this->readOneof(1);
    }

    public function hasMmasret()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.pb.MaxMessageAgeSecondsRet mmasret = 1;</code>
     * @param \Memphisphp\Pb\MaxMessageAgeSecondsRet $var
     * @return $this
     */
    public function setMmasret($var)
    {
        GPBUtil::checkMessage($var, \Memphisphp\Pb\MaxMessageAgeSecondsRet::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.MessagesRet msgret = 2;</code>
     * @return \Memphisphp\Pb\MessagesRet|null
     */
    public function getMsgret()
    {
        return $this->readOneof(2);
    }

    public function hasMsgret()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.pb.MessagesRet msgret = 2;</code>
     * @param \Memphisphp\Pb\MessagesRet $var
     * @return $this
     */
    public function setMsgret($var)
    {
        GPBUtil::checkMessage($var, \Memphisphp\Pb\MessagesRet::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.BytesRet bret = 3;</code>
     * @return \Memphisphp\Pb\BytesRet|null
     */
    public function getBret()
    {
        return $this->readOneof(3);
    }

    public function hasBret()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.pb.BytesRet bret = 3;</code>
     * @param \Memphisphp\Pb\BytesRet $var
     * @return $this
     */
    public function setBret($var)
    {
        GPBUtil::checkMessage($var, \Memphisphp\Pb\BytesRet::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.AckBasedRet abret = 4;</code>
     * @return \Memphisphp\Pb\AckBasedRet|null
     */
    public function getAbret()
    {
        return $this->readOneof(4);
    }

    public function hasAbret()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.pb.AckBasedRet abret = 4;</code>
     * @param \Memphisphp\Pb\AckBasedRet $var
     * @return $this
     */
    public function setAbret($var)
    {
        GPBUtil::checkMessage($var, \Memphisphp\Pb\AckBasedRet::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRetentions()
    {
        return $this->whichOneof("retentions");
    }

}

