<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto

namespace Memphisphp\Pb;

if (false) {
    /**
     * This class is deprecated. Use Memphisphp\Pb\StorageOpt\StorageType instead.
     * @deprecated
     */
    class StorageOpt_StorageType {}
}
class_exists(StorageOpt\StorageType::class);
@trigger_error('Memphisphp\Pb\StorageOpt_StorageType is deprecated and will be removed in the next major release. Use Memphisphp\Pb\StorageOpt\StorageType instead', E_USER_DEPRECATED);

