<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stop.proto

namespace Memphisphp\Metadata;

class Stop
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
j

stop.protopb"
StopBHZ github.com/g41797/memphisgrpc;pb Memphisphp\\Pb‚Memphisphp\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

